variable "aws_region" {
  description = "AWS region containing the Databricks workspace and payments landing bucket."
  type        = string

  validation {
    condition     = length(trimspace(var.aws_region)) > 0
    error_message = "aws_region must not be empty."
  }
}

variable "environment" {
  description = "Deployment environment."
  type        = string
  default     = "dev"

  validation {
    condition = contains(
      ["dev", "test", "stage", "prod"],
      var.environment
    )

    error_message = "environment must be dev, test, stage, or prod."
  }
}

variable "databricks_storage_credential_external_id" {
  description = <<-EOT
    External ID generated by the Databricks Unity Catalog storage credential.

    Use 0000 during the initial IAM-role bootstrap.
    Replace it with the Databricks-generated External ID after creating
    the storage credential.
  EOT

  type    = string
  default = "0000"
}

variable "enable_databricks_role_self_assume" {
  description = <<-EOT
    Whether the Unity Catalog IAM role trusts itself.

    Keep false during the initial bootstrap.
    Change to true after Databricks generates the storage credential External ID.
  EOT

  type    = bool
  default = false
}

variable "additional_tags" {
  description = "Additional AWS tags applied to project resources."
  type        = map(string)
  default     = {}
}

variable "msk_vpc_cidr" {
  description = "CIDR block for the dedicated Amazon MSK VPC."
  type        = string
  default     = "10.40.0.0/16"

  validation {
    condition     = can(cidrnetmask(var.msk_vpc_cidr))
    error_message = "msk_vpc_cidr must be a valid IPv4 CIDR block."
  }
}


variable "msk_public_subnet_cidrs" {
  description = "CIDR blocks for the two public subnets used by Amazon MSK."
  type        = list(string)

  default = [
    "10.40.10.0/24",
    "10.40.20.0/24",
  ]

  validation {
    condition = (
      length(var.msk_public_subnet_cidrs) == 2
      && alltrue([
        for cidr in var.msk_public_subnet_cidrs :
        can(cidrnetmask(cidr))
      ])
    )

    error_message = "msk_public_subnet_cidrs must contain exactly two valid IPv4 CIDR blocks."
  }
}


variable "msk_public_ingress_cidrs" {
  description = <<-EOT
    IPv4 CIDR blocks permitted to access the public IAM-authenticated
    Amazon MSK broker endpoint on TCP port 9198.

    Initially set this to the developer's current public IP /32.
    Databricks serverless outbound CIDRs are added before the
    Databricks connectivity test.
  EOT

  type = list(string)

  validation {
    condition = (
      length(var.msk_public_ingress_cidrs) > 0
      && alltrue([
        for cidr in var.msk_public_ingress_cidrs :
        can(cidrnetmask(cidr))
      ])
    )

    error_message = "msk_public_ingress_cidrs must contain at least one valid IPv4 CIDR block."
  }
}

variable "msk_kafka_version" {
  description = "Apache Kafka version used by the Amazon MSK Provisioned cluster."
  type        = string
  default     = "3.9.x"

  validation {
    condition     = length(trimspace(var.msk_kafka_version)) > 0
    error_message = "msk_kafka_version must not be empty."
  }
}


variable "msk_broker_instance_type" {
  description = "Broker instance type used by the Amazon MSK Provisioned cluster."
  type        = string
  default     = "kafka.t3.small"

  validation {
    condition     = startswith(var.msk_broker_instance_type, "kafka.")
    error_message = "msk_broker_instance_type must be a valid kafka.* broker type."
  }
}


variable "msk_broker_volume_size_gib" {
  description = "EBS storage in GiB allocated to each Amazon MSK broker."
  type        = number
  default     = 10

  validation {
    condition = (
      var.msk_broker_volume_size_gib >= 1
      && var.msk_broker_volume_size_gib <= 16384
    )

    error_message = "msk_broker_volume_size_gib must be between 1 and 16384 GiB."
  }
}


variable "enable_msk_public_access" {
  description = <<-EOT
    Whether Amazon MSK public broker endpoints are enabled.

    This MUST remain false during initial cluster creation.
    Public access is enabled only after the cluster becomes ACTIVE.
  EOT

  type    = bool
  default = false
}


variable "msk_topic_name" {
  description = "Kafka topic consumed by Databricks from Amazon MSK."
  type        = string
  default     = "payments.events.v1"

  validation {
    condition     = length(trimspace(var.msk_topic_name)) > 0
    error_message = "msk_topic_name must not be empty."
  }
}


variable "databricks_msk_service_credential_external_id" {
  description = <<-EOT
    External ID generated by the Databricks Unity Catalog
    service credential used for Amazon MSK access.

    Use 0000 during initial IAM-role bootstrap.
    Replace it after creating payments_msk_dev in Databricks.
  EOT

  type    = string
  default = "0000"
}


variable "enable_databricks_msk_role_self_assume" {
  description = <<-EOT
    Whether the Databricks MSK IAM role trusts itself.

    Keep false during the initial bootstrap.
    Set true after Databricks creates the payments_msk_dev
    service credential and provides the real External ID.
  EOT

  type    = bool
  default = false
}