variable "aws_region" {
  description = "AWS region containing the Databricks workspace and payments landing bucket."
  type        = string

  validation {
    condition     = length(trimspace(var.aws_region)) > 0
    error_message = "aws_region must not be empty."
  }
}

variable "environment" {
  description = "Deployment environment."
  type        = string
  default     = "dev"

  validation {
    condition = contains(
      ["dev", "test", "stage", "prod"],
      var.environment
    )

    error_message = "environment must be dev, test, stage, or prod."
  }
}

variable "databricks_storage_credential_external_id" {
  description = <<-EOT
    External ID generated by the Databricks Unity Catalog storage credential.

    Use 0000 during the initial IAM-role bootstrap.
    Replace it with the Databricks-generated External ID after creating
    the storage credential.
  EOT

  type    = string
  default = "0000"
}

variable "enable_databricks_role_self_assume" {
  description = <<-EOT
    Whether the Unity Catalog IAM role trusts itself.

    Keep false during the initial bootstrap.
    Change to true after Databricks generates the storage credential External ID.
  EOT

  type    = bool
  default = false
}

variable "additional_tags" {
  description = "Additional AWS tags applied to project resources."
  type        = map(string)
  default     = {}
}